### ISSUE TITLE
neanderthal-ops test failing

### ISSUE THREAD

**Issue by jsa-aerial** [aria42/tensors#3]
Hi,

Starting to play around with this and it looks very cool.  Many thanks for the work!

In running tests, I see this failure:
lein test flare.neanderthal-ops-test
java: symbol lookup error: /tmp/libneanderthal-mkl-0.17.0283772954573527292.so: undefined symbol: vdFmax

This looks like a neanderthal specific thing but thought I would ask if you have seen this?

Thanks again for the project and any info on above failure

/Jon

**Comment by aria42** [comment]
This is because you don't have Intel MKL installed. The readme mentions needing to have those native libs installed (and you also need to disable System Integrity Protection) to load libraries from non-standard locations since Intel installs these under `/opt/` typically.

**Comment by azarafrooz** [comment]
@aria42 I think you can get around the System Integrity Protection issue on MAC with these symlink tricks :
 ln -s /opt/intel/lib/* /usr/local/lib
 ln -s /opt/intel/mkl/lib/* /usr/local/lib

**Comment by jsa-aerial** [comment]
Actually, I do have it installed. But maybe not all of it that is needed for everything is moved to a visible place. I moved all the stuff that was indicated on the uncomplicate install page to /usr/local/lib and many (most?) things work. The only test that fails is the neanderthal-ops-trest.  I've been using neanderthal for some other work and not had a problem with it for that stuff.

It looks like in this case that neanderthal builds its own shareable lib (in /tmp) but that this vdFmax symbol (and code for it presumably) did not get placed in there.

I'm on Linux so the integrity thing does not affect me.

I guess I will need to ping Dragan about this in #uncomplicate

**Comment by aria42** [comment]
Oh @jsa-aerial, the issue there is you need to update to the 2018 Intel MKL release. If you'll note, `vdFmax` is used by the newer Neanderthal vector functions. I had this same problem but updating MKL fixed it for me. FYI `flare.neanderthal-ops-test` is the only test namespace which directly uses all the MKL bindings, so it would be the thing you expect to fail

**Comment by jsa-aerial** [comment]
@aria42 - that was it. as confirmed by Dragan and installing and testing. All tests pass now.

**Comment by aria42** [comment]
Closing, since seems like this is solved
